# -*- coding: utf-8 -*-
"""CNN(Brain Tumor Detector).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sHCdRa4dNw0992m6XcRvO-BelC9fVL_x

# **Importing the Libraries**
Also coding the skeleton of the CNN.
"""

#==============================================================================  
#                         PART 1
# =============================================================================
# Importing the libraries
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense

# Initialize the classifier 
classifier = Sequential()
#step 1 Convolution
classifier.add(Conv2D(32,(3,3), input_shape=(64,64,3), activation = 'relu'))
#step 2 Pooling
classifier.add(MaxPooling2D(pool_size=(2, 2)))
#step 3 Flattening
classifier.add(Flatten())
#step 4 Full connection
classifier.add(Dense(units = 128, activation = 'relu')) #units means output_dim
classifier.add(Dense(units = 1, activation = 'sigmoid'))
#compile CNN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# =============================================================================

"""# **Importing the Libraries and Loading the Image Processing**
Importing the dataset i.e. importing the images and train the images.
"""

# =============================================================================
#                            PART 2
# =============================================================================
# Importing the required classes or libraries
from keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(
        rescale=1./255,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True)

test_datagen = ImageDataGenerator(rescale=1./255)

training_set = train_datagen.flow_from_directory(
        'drive/My Drive/Datasets/dataset/training_set',
        target_size=(64, 64),
        batch_size=32,
        class_mode='binary')

test_set = test_datagen.flow_from_directory(
        'drive/My Drive/Datasets/dataset/test_set',
        target_size=(64, 64), #based on input_shape = ()
        batch_size=32,
        class_mode='binary')

classifier.fit_generator(
        training_set,
        steps_per_epoch=204,
        epochs=25,
        validation_data=test_set,
        validation_steps=49)
#==============================================================================

"""# **Importing (or) Testing the NN based on the custom images.(Now we can say wheather a person has a tumor or not.)**"""

import numpy as np
from keras.preprocessing import image
test_image = image.load_img('drive/My Drive/Datasets/Negative.jpeg', target_size=(64,64))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = classifier.predict(test_image)
training_set.class_indices
if result[0][0] >= 0.5:
  prediction = 'It is a Tumor'
else:
  prediction = 'It is not a Tumor'
print(prediction)